version: "3.7"

services:

  flask:
    build: ./fl
    container_name: fl
    restart: always
    expose:
      - 900

  nginx:
    build: ./nginx
    container_name: nginx
    restart: always
    ports:
      - "80:1234"